### ISSUE TITLE
[BUG] Copy/paste of new device URL is required in order to access QR code and Provenance Record

### ISSUE THREAD

**Issue by vjaqua** [gosqasorg/asset-provenance-tracking#280] opened 2024-09-19 21:43 UTC
**Describe the bug**
In order to access the QR Code and Provenance Record after creating New Device, I have to copy/paste the URL into a new tab. When I submit New Device, the page does not lead anywhere.![Image](https://github.com/user-attachments/assets/0b6f06d7-f7a7-45b6-b74f-3b8e4a1a3e87)
![Image](https://github.com/user-attachments/assets/c3078d66-b05f-46fd-ac12-66b23b33733b)

**Expected behavior**
After creating New Device and clicking Submit, I expect the page to automatically load the QR code and Provenance Record.

**Screenshots**
Enclosed

**Desktop:**
 - Sonoma 14.6.1
 - Chrome
 - Version 128.0.6613.138

**Additional context**
A user will assume something is wrong if the page does not automatically lead to the QR code and Provenance Record.

**Comment by bencoombs** [comment] 2024-09-23 02:39
I can reproduce this locally, however this is caused by a missing device key. When the submit button is clicked, the page should redirect to /device/<key>.

Can you try recreate the error, and when it occurs, press F12 and check if it matches the screenshot I have provided.

![Image](https://github.com/user-attachments/assets/ea196ed6-f111-4849-a142-78f6511d489f)

**Comment by vjaqua** [comment] 2024-09-24 00:17
![Image](https://github.com/user-attachments/assets/251c8367-4d30-4cad-86af-81a57b521251)

**Comment by bencoombs** [comment] 2024-09-24 00:27
Thanks for that test. Could you please repeat that but click on the console button and send a screenshot of the output? ![image](https://github.com/user-attachments/assets/48874cf3-f938-4e6d-8c6a-86710624446e)

**Comment by vjaqua** [comment] 2024-09-24 00:30
![Image](https://github.com/user-attachments/assets/6ee57164-92dc-4eae-8a9f-01e48ebfcc7b)

**Comment by vjaqua** [comment] 2024-09-24 00:31
There's a huge scroll bar of issues
![Image](https://github.com/user-attachments/assets/04360da7-c846-4c0b-92dc-faa0e23ae900)

**Comment by bencoombs** [comment] 2024-09-25 02:09
A layout error I noticed from this issue is that the footer is in the wrong place because there is no content. Fixed in: https://github.com/gosqasorg/asset-provenance-tracking/issues/285

**Closed** 2024-10-11 01:44 UTC
Labels: bug
